# Command executed while entering /invest and the player doesn't have an invest
# Let empty to not execute commands
commandInvest: 
# Show the "notInvest" message even if an invest has a __global__ region
showInGlobal: true
# Save all players each X seconds
timeToSave: 1800
# Refund player when he stops his invest (in percent)
refund-percent: 50
# Command executed when a player end his invest
commands-end:
- test
- test2
- say Le joueur %player% vient de terminer blabla
- say %displayName%